services:
  - type: web
    name: devpulse
    runtime: java
    plan: free

    buildCommand: "./gradlew clean build -x test"
    startCommand: "java -jar build/libs/devpulse.jar"

    envVars:
      - key: NEON_DB_URL
        sync: false
      - key: NEON_DB_USERNAME
        sync: false
      - key: NEON_DB_PASSWORD
        sync: false
      - key: TOKEN
        sync: false
      - key: CHAT_ID
        sync: false