spring:
  port: 8080
  application:
    name: dev-pulse
  datasource:
    url: ${NEON_DB_URL}
    username: ${NEON_DB_USERNAME}
    password: ${NEON_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

telegram:
  token: ${TOKEN}
  chat-id: ${CHAT_ID}

hugging-face:
  token: ${HF_TOKEN}
