name: DevPulse

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Make gradlew executable
        run: chmod +x gradlew

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - run: ./gradlew bootRun
