name: DevPulse

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      NEON_DB_URL: ${{ secrets.NEON_DB_URL }}
      NEON_DB_USERNAME: ${{ secrets.NEON_DB_USERNAME }}
      NEON_DB_PASSWORD: ${{ secrets.NEON_DB_PASSWORD }}
      TOKEN: ${{ secrets.TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}

    steps:
      - uses: actions/checkout@v3

      - name: Make gradlew executable
        run: chmod +x gradlew

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Build project
        run: ./gradlew clean build -x test

      - name: Run DevPulse bot (non-web)
        run: java -jar build/libs/*.jar
